#!/bin/bash

progName="algodoo"
progRealPath="/usr/share/$progName/app"
progHome="$HOME/.$progName"
progBin="Algodoo.exe"

unset WINEPREFIX
if [ ! -d $progHome ] ; then
   mkdir -p $progHome
   ln -s $progRealPath/* $progHome/

   rm $progHome/scenes
   cp -r $progRealPath/scenes $progHome/
fi

export WINEDLLOVERRIDES="msvcp90=n,b"
wine $progHome/$progBin "$@"

